1. Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.

###### Desired Output:
```Hello Sarah```

In [ ]:
# The code below almost works
name = input("Enter your name")
print("Howdy")

In [1]:
name = input("Enter your name:")
print("hello",name)

Enter your name: sarika


hello sarika


2. Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.

###### Desired Output:
```Pay: 96.25```

In [ ]:
# This first line is provided for you

hrs = input("Enter Hours:")

In [2]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")

pay = float(hrs) * float(rate)
print("Pay:", pay)

Enter Hours: 35
Enter Rate: 2.75


Pay: 96.25


3. Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.

###### Desired Output:
```498.75```

In [5]:
# Your code here
hrs = input("Enter Hours:")
h = float(hrs)

In [3]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")

h = float(hrs)
r = float(rate)

if h <= 40:
    pay = h * r
else:
    pay = 40 * r + (h - 40) * r * 1.5

print(pay)

Enter Hours: 45
Enter Rate: 10.50


498.75


4. Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
###### Score Grade
```
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
```
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

###### Desired Output:
```B```

In [ ]:
# Your code here
score = input("Enter Score: ")

In [4]:
score = input("Enter Score: ")

try:
    s = float(score)
    if s < 0.0 or s > 1.0:
        print("Error")
    elif s >= 0.9:
        print("A")
    elif s >= 0.8:
        print("B")
    elif s >= 0.7:
        print("C")
    elif s >= 0.6:
        print("D")
    else:
        print("F")
except:
    print("Error")

Enter Score:  0.8


B


5. Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

###### Desired Output:
```Pay 498.75```

In [ ]:
# Your code here
def computepay(h, r):
    return 42.37

hrs = input("Enter Hours:")
p = computepay(10, 20)
print("Pay", p)

In [5]:
def computepay(h, r):
    if h <= 40:
        return h * r
    else:
        return 40 * r + (h - 40) * r * 1.5

hrs = input("Enter Hours:")
rate = input("Enter Rate:")

p = computepay(float(hrs), float(rate))
print("Pay", p)

Enter Hours: 45
Enter Rate: 10.50


Pay 498.75


6. Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

###### Desired Output:
```
Invalid input
Maximum is 10
Minimum is 2
```

In [7]:
# Your code here
largest = None
smallest = None
while True:
    num = input("Enter a number: ")
    if num == "done":
        break
    print(num)

print("Maximum", largest)

In [6]:
largest = None
smallest = None

while True:
    num = input("Enter a number: ")
    if num == "done":
        break
    try:
        n = int(num)
        if largest is None or n > largest:
            largest = n
        if smallest is None or n < smallest:
            smallest = n
    except:
        print("Invalid input")

print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number:  7
Enter a number:  2
Enter a number:  bob


Invalid input


Enter a number:  10
Enter a number:  4
Enter a number:  done


Maximum is 10
Minimum is 2
